deploymentConfiguration:
  template: master-stack.yaml
  stackName: jenkins-ha-fleet
  capabilities:
    - CAPABILITY_NAMED_IAM
    - CAPABILITY_AUTO_EXPAND
  parameters:
    EnvironmentName: jenkins-poc
    KeyName: jenkins-demo-us-east-1
  tags:
    Project: JenkinsHA
    Environment: POC
    ManagedBy: CloudFormation