template-file-path: ./master-stack.yaml
parameters:
    EnvironmentName: jenkins-poc
    KeyName: REPLACE_WITH_YOUR_KEY_PAIR
tags:
    Project: JenkinsHA
    Environment: POC
    ManagedBy: CloudFormation