working_JenkinsLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: !Sub ${EnvironmentName}-jenkins-controller
      LaunchTemplateData:
        ImageId: !Ref LatestAmiId
        InstanceType: t3a.medium
        IamInstanceProfile:
          Name: !Ref JenkinsControllerInstanceProfile
        SecurityGroupIds:
          - !Ref JenkinsControllerSecurityGroup
        KeyName: !Ref KeyName
        BlockDeviceMappings:
          - DeviceName: /dev/xvda
            Ebs:
              VolumeSize: 30
              VolumeType: gp3
              DeleteOnTermination: true
        MetadataOptions:
          HttpTokens: required
          HttpEndpoint: enabled
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash -xe

            # Update system and install dependencies
            yum update -y
            yum install -y jq amazon-efs-utils wget curl

            # Install Java 17
            yum install -y java-17-amazon-corretto-headless

            # Mount EFS with better error handling
            JENKINS_HOME="/var/lib/jenkins"
            mkdir -p $JENKINS_HOME
            
            # Try mounting EFS with retries
            for i in {1..3}; do
              if mount -t efs ${EFSFileSystem}:/ $JENKINS_HOME; then
                echo "EFS mounted successfully"
                break
              fi
              echo "Attempt $i to mount EFS failed, retrying in 10 seconds..."
              sleep 10
            done

            # Verify mount
            if ! mountpoint -q $JENKINS_HOME; then
              echo "Failed to mount EFS after 3 attempts"
              exit 1
            fi

            # Create Jenkins user and group
            groupadd -r jenkins
            useradd -r -g jenkins -d $JENKINS_HOME -s /sbin/nologin jenkins

            # Set initial permissions
            chown -R jenkins:jenkins $JENKINS_HOME
            chmod -R 755 $JENKINS_HOME
            echo "${EFSFileSystem}:/ $JENKINS_HOME efs _netdev,tls,noatime 0 0" >> /etc/fstab

            # System optimizations
            cat << 'EOF' > /etc/security/limits.d/jenkins.conf
            jenkins soft nofile 4096
            jenkins hard nofile 8192
            jenkins soft nproc 30654
            jenkins hard nproc 30654
            EOF

            # Install Jenkins
            wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat-stable/jenkins.repo
            rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
            # Install Jenkins with retries
            for i in {1..3}; do
              if yum install -y jenkins; then
                break
              fi
              echo "Attempt $i to install Jenkins failed. Retrying..."
              sleep 10
            done

            # Create plugin directory and download required plugins
            mkdir -p $JENKINS_HOME/plugins
            cd $JENKINS_HOME/plugins

            # Download required plugins with retry logic
            echo "Downloading required plugins..."
            for plugin in ec2-fleet configuration-as-code credentials workflow-aggregator git matrix-auth authorize-project; do
              for retry in {1..3}; do
                if wget -q "https://updates.jenkins.io/download/plugins/$plugin/latest/$plugin.hpi"; then
                  break
                fi
                if [ $retry -eq 3 ]; then
                  echo "Failed to download plugin $plugin after 3 attempts"
                  exit 1
                else
                  echo "Retry $retry for plugin $plugin"
                  sleep 5
                fi
              done
            done

            # Configure Java options with proper memory settings
            cat << EOF > /etc/sysconfig/jenkins
            JENKINS_JAVA_OPTIONS="-Xmx2048m -Djava.awt.headless=true -Djenkins.install.runSetupWizard=false -Dhudson.model.DirectoryBrowserSupport.CSP="
            JENKINS_PORT="8080"
            EOF

            # Create init groovy script for security setup
            # Ensure init.groovy.d has correct permissions
            mkdir -p $JENKINS_HOME/init.groovy.d
            chown -R jenkins:jenkins $JENKINS_HOME/init.groovy.d
            chmod 755 $JENKINS_HOME/init.groovy.d
            chmod 644 $JENKINS_HOME/init.groovy.d/*.groovy
            cat << 'EOF' > $JENKINS_HOME/init.groovy.d/basic-security.groovy
            import jenkins.model.*
            import hudson.security.*
            import jenkins.install.*
            import hudson.util.Secret
            import com.cloudbees.plugins.credentials.*
            import com.cloudbees.plugins.credentials.domains.*
            import org.jenkinsci.plugins.plaincredentials.impl.*

            def instance = Jenkins.getInstance()
            
            // Ensure Jenkins is in initial setup mode
            instance.setInstallState(InstallState.INITIAL_SETUP_COMPLETED)
            
            // Wait for initialization
            Thread.sleep(10000)
            EOF

            # Fetch admin credentials from Secrets Manager with retries
            for i in {1..3}; do
              if ADMIN_CREDS=$(aws secretsmanager get-secret-value \
                --secret-id ${JenkinsAdminSecret} \
                --region ${AWS::Region} \
                --query SecretString --output text); then
                ADMIN_USER=$(echo $ADMIN_CREDS | jq -r '.username')
                ADMIN_PASSWORD=$(echo $ADMIN_CREDS | jq -r '.password')
                break
              fi
              echo "Attempt $i to fetch admin credentials failed. Retrying..."
              sleep 10
            done

            if [ -z "$ADMIN_USER" ] || [ -z "$ADMIN_PASSWORD" ]; then
              echo "Failed to fetch admin credentials"
              exit 1
            fi

            # Create user creation script with proper sequencing
            cat << EOF > $JENKINS_HOME/init.groovy.d/create-user.groovy
            import jenkins.model.*
            import hudson.security.*
            import hudson.security.csrf.DefaultCrumbIssuer

            def instance = Jenkins.getInstance()
            
            // Wait for Jenkins to be available
            Thread.sleep(15000)
            
            // Create security realm
            def hudsonRealm = new HudsonPrivateSecurityRealm(false)
            instance.setSecurityRealm(hudsonRealm)
            
            // Create admin user
            def adminUsername = "$ADMIN_USER"
            def adminPassword = "$ADMIN_PASSWORD"
            
            // Delete the user if it exists already
            def user = hudsonRealm.getAllUsers().find { it.id == adminUsername }
            if (user) {
                hudsonRealm.deleteUser(adminUsername)
            }
            
            // Create the admin user
            hudsonRealm.createAccount(adminUsername, adminPassword)
            
            // Set up authorization strategy
            def strategy = new GlobalMatrixAuthorizationStrategy()
            strategy.add(Jenkins.ADMINISTER, adminUsername)
            instance.setAuthorizationStrategy(strategy)
            
            // Enable CSRF protection
            instance.setCrumbIssuer(new DefaultCrumbIssuer(true))
            
            instance.save()
            EOF

            # Configure Jenkins CasC
            # Get EC2 Fleet ID
            EC2_FLEET_ID=$(aws cloudformation describe-stack-resources \
              --stack-name ${AWS::StackName} \
              --logical-resource-id EC2FleetConfiguration \
              --region ${AWS::Region} \
              --query 'StackResources[0].PhysicalResourceId' \
              --output text)

            cat << EOF > $JENKINS_HOME/jenkins.yaml
            jenkins:
              securityRealm:
                local:
                  allowsSignup: false
                  enableCaptcha: false
              authorizationStrategy:
                globalMatrix:
                  permissions:
                    - "Overall/Administer:$ADMIN_USER"
              systemMessage: "Jenkins HA Setup"
              numExecutors: 0
              mode: EXCLUSIVE
              scmCheckoutRetryCount: 2
              quietPeriod: 5
              remotingSecurity:
                enabled: true
              clouds:
                - ec2Fleet:
                    name: "EC2 Fleet"
                    cloudName: "AWS"
                    region: "${AWS::Region}"
                    computerConnector:
                      jnlp:
                        workDirSettings:
                          disabled: false
                          failIfWorkDirIsMissing: false
                          internalDir: "remoting"
                    idleMinutes: 10
                    minSize: 0
                    maxSize: 10
                    fleetConfig:
                      fleetId: "${EC2FleetConfiguration}"
                      fsRoot: "/home/jenkins"
                      labels: "ec2-fleet"
                      instanceCapStr: "10"
                      minimumNumberOfSpareInstances: 1
                      scaleExecutorsByWeight: true
            security:
              globalJobDslSecurityConfiguration:
                useScriptSecurity: false
              securityManager:
                enabled: true
              csrf:
                defaultCrumbIssuer:
                  enabled: true
            tool:
              git:
                installations:
                  - name: "Default"
                    home: "git"
            EOF

            # Set permissions
            chown -R jenkins:jenkins $JENKINS_HOME
            chmod 700 $JENKINS_HOME
            chmod 600 $JENKINS_HOME/jenkins.yaml

            # Set correct permissions on Jenkins home
            chown -R jenkins:jenkins $JENKINS_HOME
            chmod -R 750 $JENKINS_HOME
            
            # Configure systemd service
            cat << 'EOF' > /usr/lib/systemd/system/jenkins.service
            [Unit]
            Description=Jenkins Continuous Integration Server
            Requires=network.target
            After=network.target

            [Service]
            Type=simple
            Environment="JENKINS_HOME=/var/lib/jenkins"
            Environment="JAVA_HOME=/usr/lib/jvm/java-17-amazon-corretto"
            User=jenkins
            ExecStart=/usr/bin/java -Djava.awt.headless=true -jar /usr/share/java/jenkins.war --webroot=/var/cache/jenkins/war --httpPort=8080
            Restart=on-failure
            RestartSec=10
            SuccessExitStatus=143

            [Install]
            WantedBy=multi-user.target
            EOF

            systemctl daemon-reload

            # Configure Jenkins options
            cat << 'EOF' > /etc/sysconfig/jenkins
            JENKINS_HOME=/var/lib/jenkins
            JENKINS_JAVA_OPTIONS="-Djava.awt.headless=true -Djenkins.install.runSetupWizard=false -Dorg.apache.commons.jelly.tags.fmt.timeZone=America/New_York"
            JENKINS_PORT="8080"
            JENKINS_USER="jenkins"
            JENKINS_JAVA_CMD="/usr/lib/jvm/java-17-amazon-corretto/bin/java"
            EOF

            # Set Java environment variables
            cat << 'EOF' > /etc/profile.d/jenkins-java.sh
            export JAVA_HOME=/usr/lib/jvm/java-17-amazon-corretto
            export PATH=$JAVA_HOME/bin:$PATH
            EOF
            chmod -R 755 $JENKINS_HOME
            find $JENKINS_HOME -type f -exec chmod 644 {} \;
            find $JENKINS_HOME -type d -exec chmod 755 {} \;

            # Create Jenkins log directory with correct permissions
            mkdir -p /var/log/jenkins
            chown jenkins:jenkins /var/log/jenkins
            chmod 755 /var/log/jenkins

            # Create and set permissions for Jenkins cache directory
            mkdir -p /var/cache/jenkins
            chown jenkins:jenkins /var/cache/jenkins
            chmod 755 /var/cache/jenkins
            
            # Start Jenkins with error checking
            echo "Starting Jenkins service..."
            if ! systemctl start jenkins; then
                echo "Jenkins failed to start, checking logs..."
                journalctl -u jenkins --no-pager -n 50
                cat /var/log/jenkins/jenkins.log || true
                exit 1
            fi

            # Wait for Jenkins to initialize
            echo "Waiting for Jenkins to initialize..."
            for i in {1..30}; do
                if curl -s -f http://localhost:8080/login > /dev/null; then
                    echo "Jenkins is up and running"
                    break
                fi
                if [ $i -eq 30 ]; then
                    echo "Jenkins failed to start after 5 minutes"
                    journalctl -u jenkins --no-pager -n 50
                    cat /var/log/jenkins/jenkins.log || true
                    exit 1
                fi
                echo "Still waiting for Jenkins... (attempt $i/30)"
                sleep 10
            done
            
            # Wait for Jenkins to initialize
            echo "Waiting for Jenkins to initialize..."
            until curl -s -f http://localhost:8080/login > /dev/null || [ $? -eq 22 ]; do
              sleep 10
              echo "Still waiting for Jenkins..."
            done
            
            # Additional wait to ensure Jenkins is fully initialized
            sleep 30

            # Wait for Jenkins to be available
            timeout 300 bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' localhost:8080)" != "200" ]]; do sleep 5; done' || false

            # Signal completion to CloudFormation
            /opt/aws/bin/cfn-signal -e $? \
              --stack ${AWS::StackName} \
              --resource JenkinsASG \
              --region ${AWS::Region}